name: Deploy docs to Pages

on:
  push:
    branches: 
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    env:
      XCODE_SCHEME: "PUSDK"
      XCODE_DESTINATION: "generic/platform=iOS"
      XCODE_DERIVED_DATA_PATH: "docc"
      XCODE_DOCS_OUTPUT_PATH: "docs "
      REPOSITORY_NAME: "PayU-iOS-Swift"

    runs-on: macos-26

    steps:
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_26.5.app

    - name: Checkout
      uses: actions/checkout@v6

    - name: Show versions
      run: |
        swift --version
        xcodebuild -version

    - name: Build Docs
      run: |
        xcodebuild docbuild \
          -scheme '${{env.XCODE_SCHEME}}' \
          -destination '${{env.XCODE_DESTINATION}}' \
          -derivedDataPath '${{env.XCODE_DERIVED_DATA_PATH}}'
        $(xcrun --find docc) process-archive transform-for-static-hosting "${{env.XCODE_DERIVED_DATA_PATH}}/Build/Products/Debug-iphoneos/${{env.XCODE_SCHEME}}.doccarchive" \
          --hosting-base-path '${{env.REPOSITORY_NAME}}' \
          --output-path '${{env.XCODE_DOCS_OUTPUT_PATH}}'
        swift package resolve

    - name: Upload artifact
      id: deployment
      uses: actions/upload-pages-artifact@v5
      with:
        path: '${{env.XCODE_DOCS_OUTPUT_PATH}}'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
