name: Swift
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    env:
      XCODE_SCHEME: "PUSDK-Package"
      XCODE_DESTINATION: "platform=iOS Simulator,OS=18.4,arch=arm64,name=iPhone 16 Pro"

    runs-on: macos-15

    steps:
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Show versions
      run: |
        swift --version
        xcodebuild -version

#    - name: Build
#      run: |
#        xcodebuild -scheme ${{env.XCODE_SCHEME}} \
#                   -destination '${{env.XCODE_DESTINATION}}' \
#                   build

    - name: Run tests
      run: |
        make generate_mocks \
        xcodebuild -scheme ${{env.XCODE_SCHEME}} \
                   -destination '${{env.XCODE_DESTINATION}}' \
                   -testLanguage en \
                   -testRegion en_US \
                   test
